In [328]:
import numpy as np
import pandas as pd
import sklearn.svm as svm
import random
from sklearn import metrics
from sklearn.decomposition import PCA

In [329]:
# a
N_train = 100
N_test = 50

data = pd.read_csv('iris.csv', header=None)

features = data.iloc[:, :4].apply(
    lambda x: (x - x.mean()) / x.std()
)

labels = data.iloc[:, 4]

pca = PCA(n_components=2)
components = pca.fit_transform(features)

data = pd.DataFrame(components)
data['label'] = labels.values

indices = data.index.to_list()
random.shuffle(indices)
train_indices = random.sample(indices, N_train)
test_indices = np.setdiff1d(indices, train_indices)

train = data.loc[train_indices]
test = data.loc[test_indices]

train_data = train.iloc[:, :-1]
train_label = train.iloc[:, -1]

test_data = test.iloc[:, :-1]
test_label = test.iloc[:, -1]


In [330]:
# b
clf = svm.SVC(kernel='linear')
clf.fit(train_data, train_label)
aprox_label = clf.predict(test_data)

In [331]:
# c
conf_matrix = metrics.confusion_matrix(test_label, aprox_label)
print(conf_matrix)

acc = metrics.accuracy_score(test_label, aprox_label)
err = 1 - acc
print("Acuratete:")
print(acc)
print("Eroare:")
print(err)


[[21  0  0]
 [ 0  8  1]
 [ 0  3 17]]
Acuratete:
0.92
Eroare:
0.07999999999999996


In [332]:
# d
clf = svm.SVC()
clf.fit(train_data, train_label)
aprox_label = clf.predict(test_data)

conf_matrix = metrics.confusion_matrix(test_label, aprox_label)
print(conf_matrix)

acc = metrics.accuracy_score(test_label, aprox_label)
err = 1 - acc
print("Acuratete:")
print(acc)
print("Eroare:")
print(err)


[[21  0  0]
 [ 0  8  1]
 [ 0  3 17]]
Acuratete:
0.92
Eroare:
0.07999999999999996
